### ISSUE TITLE
Cross-browser modal issue in Safari

### ISSUE THREAD

**Issue by scloo** [GoogleChrome/dialog-polyfill#105] opened 2016-05-07 16:21 UTC
Looks like the modal functionality has issue on the Safari. I have a login dialog modal. On firing up, the dialog came up fine. The moment you click any where on the screen (including the dialog), everything becomes unresponsive to the mouse click, including the dialog itself. I will not be able to access the form input fields or anything else for that matter.

Basically the whole page gets locked out including the dialog. To unlock it, I go into the console and disable the z-index for the _dialog_overlay. But this disables the dialog_overlay and hence breaking the modal functionality.

Is there any workaround for this problem? Is this a known modal issue with other browser like Safari?

Thanks

**Comment by scloo** [comment] 2016-05-07 17:37
If I remove the 'bottom: 0" from the css for _dialog_overlay ,the dialog becomes available. But it basically disable the modal functionality, making it like the regular dialog without modal.

I have tested your modal demo in Safari and it works fine. I just can't see what I have missed. Unless the fact that I am running under Backbone JS view environment might have complicated the case. But it works without a hitch under Chrome.

**Comment by prasadsilva** [comment] 2016-06-08 22:00
I'm running into this too, but I think on my end the issue is related to the following limitation (per README): 

**They should be a child of <body> or have parents without layout (aka, no position absolute or relative elements)**

I'm using react-mdl, and the dialog elements are being created inside the content section of a page that uses layout to support a responsive header and a navbar.

**Comment by 5amfung** [comment] 2016-06-19 06:57
I have similar issue with Safari that the modal doesn't close.  However hitting the `esc` key did close the modal.

**Comment by samthor** [comment] 2016-06-19 08:16
@Garbee look at @prasadsilva 's comment.

A nice fix is to set them to be `position: fixed` (why this wasn't part of the spec I have no idea) and fix the related CSS of that. That way they just live in the middle of the screen regardless of viewport and don't care about layout.

**Comment by Garbee** [comment] 2016-06-19 11:24
Ah, interesting. I'll take a look at this on Thursday or Friday if I have time. That sounds like a great fix.

**Comment by samthor** [comment] 2017-01-24 00:41
Closing this as it's related to incorrect use of stacking context. We now warn if you're making a mistake, and also are more permissive, so incorrect usage might still work: #131

**Closed** 2017-01-24 00:42 UTC
