### ISSUE TITLE
returnValue isn't always set properly

### ISSUE THREAD

**Issue by marekjalovec** [GoogleChrome/dialog-polyfill#122] opened 2016-12-16 17:37 UTC
issue mentioned in #102 is still valid. if you have a two button dialog view type=submit and value, nothing more, you don't get the value of used button. works in native implementation.

sample see http://demo.agektmr.com/dialog/ -> Integration with a form

**Comment by samthor** [comment] 2017-01-22 22:21
I can't reproduce this. The `returnValue` is set to the value of the used button in my tests using Firefox (and Chrome w/o polyfill).

See the code checked in here: https://github.com/GoogleChrome/dialog-polyfill/commit/7e49e8d34e9111fa2329780650304057796ed05b

Can you elaborate or give me a clearer repro case?

**Comment by samthor** [comment] 2017-01-22 22:22
(Also note that hitting enter while focused on the `input type="text"` sets the `returnValue` to the current value of the field. That's intentional and is the case natively too.)

**Comment by samthor** [comment] 2017-02-13 10:13
Can't repro with Firefox. Closing.

**Closed by samthor** 2017-02-13 10:13 UTC
